# Generated by Django 2.2 on 2019-07-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_apis', '0002_auto_20190719_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='availableFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='availableTo',
            field=models.DateTimeField(),
        ),
    ]
