# Generated by Django 2.2 on 2019-07-19 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_apis', '0003_auto_20190719_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='availableFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='availableTo',
            field=models.DateField(),
        ),
    ]
