# Generated by Django 2.2 on 2019-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_apis', '0004_auto_20190719_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='availableFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='availableTo',
            field=models.DateTimeField(),
        ),
    ]
